### ISSUE TITLE
How to use local version of xcpretty with test_center?

### ISSUE THREAD

**Issue by hiteshjain4** [lyndsey-ferguson/fastlane-plugin-test_center#127]
### Question Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

### Question Subject

How can i use local version of xcpretty with test_center ?

#### Question Description

I'm using test_center tool with Earlgrey automation. While using it I came across an issue with regards to html report.
I have opened an issue: https://github.com/xcpretty/xcpretty/issues/351 with xcpretty. 
I made a Pull Request to solve the issue as well : https://github.com/xcpretty/xcpretty/pull/352 , But since nobody is active there it is not merged.

I wanted to use my version of xcpretty (https://github.com/hiteshjain4/xcpretty/tree/hiteshjain4-Piechart-%26-TestCount) with test_center plugin, can you tell me how can I achieve it?

Also, I tried creating an alias for my version of xcpretty, and then tried running multi_scan, but it seems like it is not picking the correct version of xcpretty (while the same is working when I tried it manually).

Can you suggest to me if I can use my version of xcpretty with test_center? And if yes how can I achieve that? 

Thanks

**Comment by lyndsey-ferguson** [comment]
Hello @hiteshjain4 give me some time to look into this. There may be something that we can look into that will make `multi_scan` pick up your version of `xcpretty` instead of a default.

How do you know it is using the regular version. Are you just basing that off the failure to create the expected html report?

**Comment by hiteshjain4** [comment]
Hi @lyndsey-ferguson : In the updated version, I have some code that creates pie chart, and also gives correct test case count. So yes I'm basing that on the expected Html report.

**Comment by lyndsey-ferguson** [comment]
@hiteshjain4 reviewing [your changes](https://github.com/xcpretty/xcpretty/compare/master...hiteshjain4:hiteshjain4-Piechart-&-TestCount?expand=1), it seems like these changes could be made _after_ `xcpretty` is complete. In fact after a `scan` or `multi_scan`.

You would:
# Add the css to the HTML file
# Add the piechart section along with the script tags to the HTML file
# fix the test count in the HTML file. You can parse it with REXML.

In fact, it think you could make a fastlane plugin that does just this and become fastlane-famous 😄

**Comment by lyndsey-ferguson** [comment]
Oh, and I could give you some initial guidance with REXML if you have questions.

**Comment by hiteshjain4** [comment]
Hi @lyndsey-ferguson: Thanks for the suggestion. Yeah, this seems to be the best thing to do here. I will start looking into this.

But since I'm pretty new to ruby (REXML) give me some time to learn about these technologies, and get myself familiarize with Fastlane/test_center.

I would be needing your help with this and with getting Fastlane famous 😄

**Comment by lyndsey-ferguson** [comment]
The [code that I wrote for collate_html_reports](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb) may give you the guidance you need. Learning the basics of XPath is a must.

I'll leave this Issue open so that you can ask your questions here.

**Comment by lyndsey-ferguson** [comment]
I'm going to close the issue so I get better points in the Fastlane Available Plugins page. I'll keep the conversation unlocked so that we can still communicate here if you need help @hiteshjain4 .

**Comment by jainhitesh3** [comment]
Hi @lyndsey-ferguson, Thanks to your suggestion I have created a method that updates the HTML file. Please have a look [UpdateXCprettyReport](https://github.com/jainhitesh3/UpdateXCprettyReport), and also could you please do suggest me if anything else can be added or any change is required here.

Currently: 
* The HTML File location is hardcoded as I'm not sure of how to get that from Fastfile lane. Do you have something that can help me with this?
* Instead of using REXML, I'm using nokogiri gem.

**Comment by lyndsey-ferguson** [comment]
I going to take up your offer and make some suggestions to you.

First, you should reconsider using REXML rather than nokogiri. I, and my team, ran into so many problems installing that gem because it had to built locally. That required the local env to be set up exactly as the author(s) anticipated.

Often, OS upgrades would break nokogiri.

Yes, REXML is not as easy to use as nokogiri is, but one can learn it.

**Comment by lyndsey-ferguson** [comment]
I also suggest that you make a `fastlane` plugin that calls this gem. It is fine to have a gem because not everyone uses fastlane, but if you create a plugin, it appears in [fastlane's available plugins](https://docs.fastlane.tools/plugins/available-plugins/) and the list from calling `fastlane search_plugins`.

**Comment by lyndsey-ferguson** [comment]
Also, I would not name this `UpdateXCprettyReport` as that is highly generic. You could name it `EnhanceXCPrettyReport`. You cannot name it `FixXCPrettyReport` as you are also adding a nice piechart.
