### ISSUE TITLE
Test log on console when using multi scan with parallel_testrun_count option

### ISSUE THREAD

**Issue by thuyvu113** [lyndsey-ferguson/fastlane-plugin-test_center#162]
#### Question Description
When I use multi scan tool with parallel_testrun_count option, I would like to see the log of current testing process. However, this log is only available when the testing job is done. 

This what I got when the testing jobs were running:
```
Starting test run 1
Starting test run 2
Starting test run 3
Starting test run 4
```

Is it possible to show the current log of testing of all testing clone?

**Comment by technomark** [comment]
To refine this a bit - how about just printing `Test runner 1: testSomethingARather() passed [44 seconds]`
`Test runner 2: testSomethingElse() failed [43 seconds] - couldn't find element xyz`

so that way we get an idea of the progress but don't get a whole lot of jumbled mess.

**Comment by lyndsey-ferguson** [comment]
Unfortunately, it was very difficult for me to have parallel processes printing sensible console messages.
1. because they are in parallel, they would write when they wanted to. This means that one processes methods  would write in the middle of another one and one could not decipher which message came from which.
2. Even if I was able to lock down the STDOUT system (I probably could with some effort), it requires some hackery to tweak how `fastlane's` `scan` prints out the method to make it obvious which worker is printing the message. This would be fragile as I would be modifying `scan's` "private" methods and it could break when they change it.

**Comment by lyndsey-ferguson** [comment]
I'm open to PRs if you can figure it out, but for now, I'm going to close this Issue.

**Comment by lyndsey-ferguson** [comment]
Also, one other thing you may be able to do if you want to invest, is re-use the pipes between each subprocess and the parent process to send each line. The main process would be responsible for printing the messages. That way, each message would _not_ be be writing in the middle of the other message.
