### ISSUE TITLE
try_count retries all tests instead of just the failing test

### ISSUE THREAD

**Issue by frankh** [lyndsey-ferguson/fastlane-plugin-test_center#203]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
I have a Fastfile with a lane definition including:

```
multi_scan(
      try_count: 3,
      scheme: test_scheme,
      devices: test_device,
      only_testing: ["UITests/AccountFlowTest"],
      xcargs: "OTHER_SWIFT_FLAGS='-D TAKE_SCREENSHOTS'",
      derived_data_path: derived_data_path,
      code_coverage: true,
      fail_build: true, # stop if the tests fail
      skip_build: true,
      test_without_building: true,
      output_types: "junit",
      output_files: "results.xml",
      output_directory: './test_results/'
    )
```

There's one particularly flaky test that I want to retry if it fails, however when it fails all the tests are retried - it's passing all the tests individually into `only_testing` instead of the just the failed one

Scan summary:
```
+------------------------------------------------+-----------------------------------------------------------------------+
|                                                Summary for scan 2.142.0                                                |
+------------------------------------------------+-----------------------------------------------------------------------+
| scheme                                         |  Tests                                                                |
| only_testing                                   | ["UITests/AccountFlowTest"]                                           |
| xcargs                                         | OTHER_SWIFT_FLAGS='-D TAKE_SCREENSHOTS' -parallel-testing-enabled NO  |
| derived_data_path                              | DerivedData                                                           |
| code_coverage                                  | true                                                                  |
| fail_build                                     | true                                                                  |
| skip_build                                     | true                                                                  |
| test_without_building                          | true                                                                  |
| output_types                                   | junit                                                                 |
| output_files                                   | results.xml                                                           |
| output_directory                               | /Users/anka/app/test_results                                          |
| workspace                                      | ./proj.xcworkspace                                                    |
| skip_detect_devices                            | false                                                                 |
| force_quit_simulator                           | false                                                                 |
| reset_simulator                                | false                                                                 |
| disable_slide_to_type                          | true                                                                  |
| reinstall_app                                  | false                                                                 |
| clean                                          | false                                                                 |
| open_report                                    | false                                                                 |
| buildlog_path                                  | output/buildlogs/scan                                                 |
| include_simulator_logs                         | true                                                                  |
| should_zip_build_products                      | false                                                                 |
| result_bundle                                  | false                                                                 |
| use_clang_report_name                          | false                                                                 |
| disable_concurrent_testing                     | true                                                                  |
| build_for_testing                              | false                                                                 |
| slack_use_webhook_configured_username_and_icon | false                                                                 |
| slack_username                                 | fastlane                                                              |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png        |
| skip_slack                                     | false                                                                 |
| slack_only_on_failure                          | false                                                                 |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                                     |
| xcode_path                                     | /Applications/Xcode.app                                               |
+------------------------------------------------+-----------------------------------------------------------------------+
```

When it retries it adds all the tests into only_testing:

```
only_testing | ["UITests/AccountFlowTest/testWallet", 
"UITests/AccountFlowTest/testBuyFromDashboard", 
"UITests/AccountFlowTest/testBuyWithServerError", 
"UITests/AccountFlowTest/testRecurringPaymentDetail", 
"UITests/AccountFlowTest/testTradeTrayInTransactions", 
"UITests/AccountFlowTest/testWalletDepositDisabled", 
"UITests/AccountFlowTest/testRecurringSetup_aggressive", 
"UITests/AccountFlowTest/testTransactionsWithNoBalance", 
"UITests/AccountFlowTest/testEmptyTransactionsNoBalance", 
"UITests/AccountFlowTest/testWalletWithdrawalDisabled", 
"UITests/AccountFlowTest/testTransactionDetailsWithConfirmation", 
"UITests/AccountFlowTest/testBuy", 
"UITests/AccountFlowTest/testSend"]
```

I haven't included more output as i'd need to redact a lot of it. Let me know what other information would be helpful

**Comment by frankh** [comment]
I managed to fix it, I needed to set `skip_build: false`, with it set to true it first ran all the tests and if one failed it re-ran them all again, then worked as expected

**Comment by raviTokopedia** [comment]
I am facing the same problem and this solution doesn't seem to work for me.

```
multi_scan(
      project: 'ios/Project.xcodeproj',
      scheme: 'ProjectUITests',
      destination: "name=#{deviceName}",
      clean: false,
      derived_data_path: './d',
      only_testing: ['ProjectUITests/ProjectPerformanceTests'],
      output_types: 'junit',
      output_files: 'report.junit',
      build_for_testing: true,
      result_bundle: true,
      fail_build: false,
      skip_build: false,
      output_directory: 'reports',
      configuration: 'Debug',
      prelaunch_simulator: false,
      xcargs: xcargs,
      disable_concurrent_testing: true,
      retry_test_runner_failures: true,
      try_count: 3,
      testrun_completed_block: test_run_block
)
```

It retries all the tests in the suit instead of just the failed one. When I checked the junit file, it seems to have no logs, even though the parallel testing option is disabled.

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites tests='0' failures='0'/>
```

It reports 0 number of tests which should have been 2 and 0 number of failures which should have been 1.
<pre>
** TEST EXECUTE FAILED **
[19:11:15]: Exit status: 65
[19:11:16]: Successfully sent Slack notification
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 0 |
| Number of failures | 0 |
+--------------------+---+

[19:11:16]: Everything is fine, let's continue to try 2 for batch 1
[19:11:18]: Starting scan #2 with 2 tests for batch #1.
</pre>

Scan summary:
<pre>
+------------------------------------------------+---------------------------------------------------------------------------------+
|                                                     Summary for scan 2.134.0                                                     |
+------------------------------------------------+---------------------------------------------------------------------------------+
| project                                        | ios/Project.xcodeproj                                                           |
| scheme                                         | ProjectUITests                                                                  |
| clean                                          | false                                                                           |
| derived_data_path                              | ./d                                                                             |
| only_testing                                   | ["ProjectUITests/ProjectPerformanceTests/testHomePLT",                          |
|                                                | "ProjectUITests/ProjectPerformanceTests/testOfficialStorePLT"]                  |
| output_types                                   | junit                                                                           |
| output_files                                   | report.junit                                                                    |
| fail_build                                     | false                                                                           |
| skip_build                                     | false                                                                           |
| output_directory                               | /Users/test/Projects/ios-project/reports/ProjectUITests-batch-1                 |
| configuration                                  | Debug                                                                           |
| prelaunch_simulator                            | false                                                                           |
| xcargs                                         | -quiet -UseNewBuildSystem=YES OTHER_SWIFT_FLAGS='-DPERFORMANCE_TESTING'         |
|                                                | GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS                     |
|                                                | PERFORMANCE_TESTING=1'  -parallel-testing-enabled NO -resultBundlePath          |
|                                                | '/Users/test/Projects/ios-project/reports/ProjectUITests-batch-1/repo           |
|                                                | rt-2.xcresult'                                                                  |
| disable_concurrent_testing                     | true                                                                            |
| skip_detect_devices                            | false                                                                           |
| force_quit_simulator                           | false                                                                           |
| reset_simulator                                | false                                                                           |
| reinstall_app                                  | false                                                                           |
| app_identifier                                 | com.project.Project                                                             |
| xctestrun                                      | ./d/Build/Products/ProjectUITests_iphoneos13.5-arm64.xctestrun                  |
| open_report                                    | false                                                                           |
| buildlog_path                                  | ~/Library/Logs/scan                                                             |
| include_simulator_logs                         | false                                                                           |
| should_zip_build_products                      | false                                                                           |
| use_clang_report_name                          | false                                                                           |
| slack_use_webhook_configured_username_and_icon | false                                                                           |
| slack_username                                 | fastlane                                                                        |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                  |
| skip_slack                                     | false                                                                           |
| slack_only_on_failure                          | false                                                                           |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                                               |
| xcode_path                                     | /Applications/Xcode.app                                                         |
| build_for_testing                              | false                                                                           |
| result_bundle                                  | false                                                                           |
+------------------------------------------------+---------------------------------------------------------------------------------+
</pre>

**PS: I am running this in an iOS 13.5, iPhone 7 device and not the simulator.**

**Comment by Ravi61** [comment]
I am facing the same problem and this solution doesn't seem to work for me.

```
multi_scan(
      project: 'ios/Project.xcodeproj',
      scheme: 'ProjectUITests',
      destination: "name=#{deviceName}",
      clean: false,
      derived_data_path: './d',
      only_testing: ['ProjectUITests/ProjectPerformanceTests'],
      output_types: 'junit',
      output_files: 'report.junit',
      build_for_testing: true,
      result_bundle: true,
      fail_build: false,
      skip_build: false,
      output_directory: 'reports',
      configuration: 'Debug',
      prelaunch_simulator: false,
      xcargs: xcargs,
      disable_concurrent_testing: true,
      retry_test_runner_failures: true,
      try_count: 3,
      testrun_completed_block: test_run_block
)
```

It retries all the tests in the suit instead of just the failed one. When I checked the junit file, it seems to have no logs, even though the parallel testing option is disabled.

```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites tests='0' failures='0'/>
```

It reports 0 number of tests which should have been 2 and 0 number of failures which should have been 1.
<pre>
** TEST EXECUTE FAILED **
[19:11:15]: Exit status: 65
[19:11:16]: Successfully sent Slack notification
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 0 |
| Number of failures | 0 |
+--------------------+---+

[19:11:16]: Everything is fine, let's continue to try 2 for batch 1
[19:11:18]: Starting scan #2 with 2 tests for batch #1.
</pre>

Scan summary:
<pre>
+------------------------------------------------+---------------------------------------------------------------------------------+
|                                                     Summary for scan 2.134.0                                                     |
+------------------------------------------------+---------------------------------------------------------------------------------+
| project                                        | ios/Project.xcodeproj                                                           |
| scheme                                         | ProjectUITests                                                                  |
| clean                                          | false                                                                           |
| derived_data_path                              | ./d                                                                             |
| only_testing                                   | ["ProjectUITests/ProjectPerformanceTests/testHomePLT",                          |
|                                                | "ProjectUITests/ProjectPerformanceTests/testOfficialStorePLT"]                  |
| output_types                                   | junit                                                                           |
| output_files                                   | report.junit                                                                    |
| fail_build                                     | false                                                                           |
| skip_build                                     | false                                                                           |
| output_directory                               | /Users/test/Projects/ios-project/reports/ProjectUITests-batch-1                 |
| configuration                                  | Debug                                                                           |
| prelaunch_simulator                            | false                                                                           |
| xcargs                                         | -quiet -UseNewBuildSystem=YES OTHER_SWIFT_FLAGS='-DPERFORMANCE_TESTING'         |
|                                                | GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS                     |
|                                                | PERFORMANCE_TESTING=1'  -parallel-testing-enabled NO -resultBundlePath          |
|                                                | '/Users/test/Projects/ios-project/reports/ProjectUITests-batch-1/repo           |
|                                                | rt-2.xcresult'                                                                  |
| disable_concurrent_testing                     | true                                                                            |
| skip_detect_devices                            | false                                                                           |
| force_quit_simulator                           | false                                                                           |
| reset_simulator                                | false                                                                           |
| reinstall_app                                  | false                                                                           |
| app_identifier                                 | com.project.Project                                                             |
| xctestrun                                      | ./d/Build/Products/ProjectUITests_iphoneos13.5-arm64.xctestrun                  |
| open_report                                    | false                                                                           |
| buildlog_path                                  | ~/Library/Logs/scan                                                             |
| include_simulator_logs                         | false                                                                           |
| should_zip_build_products                      | false                                                                           |
| use_clang_report_name                          | false                                                                           |
| slack_use_webhook_configured_username_and_icon | false                                                                           |
| slack_username                                 | fastlane                                                                        |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                  |
| skip_slack                                     | false                                                                           |
| slack_only_on_failure                          | false                                                                           |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                                               |
| xcode_path                                     | /Applications/Xcode.app                                                         |
| build_for_testing                              | false                                                                           |
| result_bundle                                  | false                                                                           |
+------------------------------------------------+---------------------------------------------------------------------------------+
</pre>

**PS: I am running this in an iOS 13.5, iPhone 7 device and not the simulator.**

**Comment by lyndsey-ferguson** [comment]
Can you create a new issue with this info included? Make sure you look at the template as you create the ticket to make sure you provide everything.

**Comment by Ravi61** [comment]
Done, here https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/225 @lyndsey-ferguson
