### ISSUE TITLE
How to specify test_output folder location in multi_scan

### ISSUE THREAD

**Issue by ssharma0312** [lyndsey-ferguson/fastlane-plugin-test_center#288]
### Question Checklist

`fastlane-plugin-test_center` --> version 3.11.5
using multi_scan below code
`multi_scan(
      workspace: "ABC.xcworkspace",
      scheme: options[:scheme],
      code_coverage: true,
      output_types: 'junit',
      output_files: "junit.xml",
      try_count: 3, # retry _failing_ tests up to three times^1.
      batch_count: 6,
      code_coverage: true,
      parallel_testrun_count: 6, # run subsets of your tests on parallel simulators^2
      testrun_completed_block: test_run_block,
      devices: "iPhone 11",
      result_bundle: "TestResults" # To generate test reports
    )`

Currently this produces following folder (I have two test target in my project ABCTest and ABCUITest):
ProjectDirectory/fastlane/test_output/ABCTest/report.test_result
ProjectDirectory/fastlane/test_output/ABCUITest/report.test_result

Since I have multiple CI/CD jobs targeting different branches, I want to pass branch name in the test output folder path so results from other job don't overwrite. Where in the multi_scan I specify test_output folder name or path?

**Comment by lyndsey-ferguson** [comment]
I'll teach [you how to fish rather than giving you the answer directly](https://en.wiktionary.org/wiki/give_a_man_a_fish_and_you_feed_him_for_a_day;_teach_a_man_to_fish_and_you_feed_him_for_a_lifetime).

1. Go to the [README](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center#features)
2. Find and click the `multi_scan` action.
3. Navigate to the Parameters section and click the link to the `scan` parameters.
4. Look for the parameter that controls the directory for where reports are stored.

**Comment by ssharma0312** [comment]
Added parameter `output_directory` = "./fastlane/test_output/" + options[:branch]
Will update here once pipeline job completes.

**Comment by ssharma0312** [comment]
It works

**Comment by lyndsey-ferguson** [comment]
Teach your friends! 🤗
