### ISSUE TITLE
Feature Request: Add support for Invocation based tests

### ISSUE THREAD

**Issue by yousefhamza** [lyndsey-ferguson/fastlane-plugin-test_center#97]
### Feature Request
Add support for Invocation based tests like Kiwi

#### Motivation Behind Feature
Our tests have a mix of XCTests and Kiwi tests, `multi_scan` seems to be running only the XCTest tests by passing them to scan as `only_testing`

#### Feature Description
`multi_scan` should run the first `scan` run without `only_testing` setting as when the tests run they will be added to xctestrun file then only pass the failing tests in `only_testing` for the subsequent runs.

Note that for subsequent test re-runs the `only_testing` should be on the file of the tests that failed not the specific test that fails because they don't exist and thus the test runs will exit immediately with 0 tests run.

#### Alternatives or Workarounds
None, at least a one that's convenient. I thought maybe I could run the tests the first run myself then start multiscan but that means test time increases by a factor of 2x.

**Comment by lyndsey-ferguson** [comment]
Thank you @yousefhamza for the feature request. Very interesting. Could you provide a sample project with a sample fastlane?

I'm curious if there is a way to detect the Kiwi tests without having to run `scan` first so that the flow of the code is similar. That would be something I would like to look at first. 

The other option would be to explicitly disable the plugin to use the `only_testing` Scan option on the first run as you suggest. Or, if there is a way to at least determine if it is a Kiwi test project to disable the only_testing option for the first run.

**Comment by yousefhamza** [comment]
The solution I had in mind was adding an option for `multi_scan`.
Something like `invocation_based_tests: true/false #default to false`.

I will provide a sample app ASAP 👍

**Comment by yousefhamza** [comment]
Hi, this is a sample app with a Kiwi test and the plugin integrated 👍 

Run:
`bundle exec fastlane unit_tests`

[KiwiDemo.zip](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/3170237/KiwiDemo.zip)

**Comment by lyndsey-ferguson** [comment]
Thank you! Note: this is not my top priority, but when I start working on this, you'll see that I move it into the in progress column in the project.

**Comment by lyndsey-ferguson** [comment]
Released 🎉. Thanks for the great PR @yousefhamza !!
Fix in [v3.7.0](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.7.0)
